
export const resultI: string[][] = [ 
['SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE'],
['SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE'],
['SPACE','SPACE','POLYANET','SPACE','SPACE','SPACE','SPACE','SPACE','POLYANET','SPACE','SPACE'],
['SPACE','SPACE','SPACE','POLYANET','SPACE','SPACE','SPACE','POLYANET','SPACE','SPACE','SPACE'],
['SPACE','SPACE','SPACE','SPACE','POLYANET','SPACE','POLYANET','SPACE','SPACE','SPACE','SPACE'],
['SPACE','SPACE','SPACE','SPACE','SPACE','POLYANET','SPACE','SPACE','SPACE','SPACE','SPACE'],
['SPACE','SPACE','SPACE','SPACE','POLYANET','SPACE','POLYANET','SPACE','SPACE','SPACE','SPACE'],
['SPACE','SPACE','SPACE','POLYANET','SPACE','SPACE','SPACE','POLYANET','SPACE','SPACE','SPACE'],
['SPACE','SPACE','POLYANET','SPACE','SPACE','SPACE','SPACE','SPACE','POLYANET','SPACE','SPACE'],
['SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE'],
['SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE','SPACE']]
 
